FROM python:3.12-slim

WORKDIR /app

# Instala deps primeiro (cache layer)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o código da app
COPY server.py .
COPY index.html .

# Expõe a porta 5000
EXPOSE 5000

# Roda o Flask
CMD ["python", "server.py"]